# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'capstone_mainpage' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'Parchment'

  # Pods for capstone_mainpage

  target 'capstone_mainpageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'capstone_mainpageUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
