# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# testing
workspace 'capstone_mainpage'


target 'capstone_mainpage' do
  project './capstone_mainpage.xcodeproj'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Parchment'
end

  # Pods for capstone_mainpage

target 'CBarcode' do
  project './CBarcode.xcodeproj'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CBarcode
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'SVProgressHUD'
  pod 'ChameleonFramework'
  pod 'SCLAlertView'
  pod 'TextFieldEffects'
  pod 'PMSuperButton'

end


